pipelines:
  fuelling-the-debate:
    group: Static-Websites
    label_template: "${COUNT}"
    materials:
      fuelling-the-debate-git:
        git: https://github.com/ukparliament/fuellingthedebate.parliament.uk.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval: manual
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - checkout_to_release
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release


environments:
  Web.LIVE:
    pipelines:
      - fuelling-the-debate